# Pandas Work

pip install pandas

In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\instructor\appdata\roaming\python\python313\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\instructor\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\instructor\appdata\roaming\python\python313\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\instructor\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 2.4 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.8 MB 4.9 MB/s eta 0:00:02
   ----------- ---------------------------- 2.9/9.8 MB 5.0 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.8 MB 6.0 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/9.8 MB 7.1 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.8 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 6.9 MB/s eta 0:00:00
Installing collected packages: pandas
Successfully installed pandas-3.0.5
Note: you may need to restart the kernel to use updated packages.

WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame({
    "name": ["ali", "ahmad", "shamir"],
    "marks": [87, 98, 78],
    "city": ["Karachi", "lahore", "pindi"]
})

In [5]:
df

     name  marks     city
0     ali     87  Karachi
1   ahmad     98   lahore
2  shamir     78    pindi

In [6]:
df.columns

Index(['name', 'marks', 'city'], dtype='str')

In [7]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [9]:
s = pd.Series([3,5,7,9], index=['a', 'b', 'c','d'])
s

a    3
b    5
c    7
d    9
dtype: int64

In [11]:
df = pd.read_csv("data.csv")
df.sample()

    Order_ID  Age Gender Product  Quantity  Unit_Price  Rating
48      1049   58   Male  Laptop         1         890     4.8

In [12]:
df.head()

   Order_ID  Age  Gender     Product  Quantity  Unit_Price  Rating
0      1001   23    Male      Laptop         1         850     4.5
1      1002   31  Female       Phone         2         600     4.2
2      1003   45    Male  Headphones         3          80     4.0
3      1004   28  Female      Tablet         1         350     4.7
4      1005   36    Male    Keyboard         2          45     3.8

In [13]:
df.tail()

    Order_ID  Age  Gender   Product  Quantity  Unit_Price  Rating
45      1046   34  Female    Tablet         2         330     4.7
46      1047   20    Male  Keyboard         2          47     3.5
47      1048   43  Female     Mouse         5          23     4.2
48      1049   58    Male    Laptop         1         890     4.8
49      1050   30  Female     Phone         1         640     4.6

In [14]:
df.tail(7)

    Order_ID  Age  Gender     Product  Quantity  Unit_Price  Rating
43      1044   26  Female       Phone         2         630     4.5
44      1045   47    Male  Headphones         3          78     4.0
45      1046   34  Female      Tablet         2         330     4.7
46      1047   20    Male    Keyboard         2          47     3.5
47      1048   43  Female       Mouse         5          23     4.2
48      1049   58    Male      Laptop         1         890     4.8
49      1050   30  Female       Phone         1         640     4.6

In [16]:
df[df["Order_ID"]==1011]

    Order_ID  Age Gender   Product  Quantity  Unit_Price  Rating
10      1011   26   Male  Keyboard         3          50     4.0

In [17]:
df.describe()

         Order_ID        Age   Quantity  Unit_Price     Rating
count    50.00000  50.000000  50.000000   50.000000  50.000000
mean   1025.50000  36.060000   2.100000  348.900000   4.284000
std      14.57738  10.210859   1.147313  327.188908   0.350137
min    1001.00000  20.000000   1.000000   22.000000   3.500000
25%    1013.25000  28.000000   1.000000   48.500000   4.000000
50%    1025.50000  34.500000   2.000000  325.000000   4.300000
75%    1037.75000  43.750000   3.000000  617.500000   4.600000
max    1050.00000  58.000000   5.000000  950.000000   4.900000

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    50 non-null     int64
 1   Age         50 non-null     int64
 2   Gender      50 non-null     str
 3   Product     50 non-null     str
 4   Quantity    50 non-null     int64
 5   Unit_Price  50 non-null     int64
 6   Rating      50 non-null     float64
dtypes: float64(1), int64(4), str(2)
memory usage: 2.9 KB

In [20]:
df.shape

(50, 7)