## Pandas

In [2]:
import pandas as pd

In [3]:
s = pd.Series([1,2,3,4], index=["a","b","c","d"])
print(s)

a    1
b    2
c    3
d    4
dtype: int64

In [4]:
s["a"]

np.int64(1)

In [5]:
df = pd.DataFrame(
    {
        "name":["ali", "shah", "amjad"],
        "age": [23, 25, 26],
        "marks": [89, 78 , 76]
    }
)

In [6]:
df

    name  age  marks
0    ali   23     89
1   shah   25     78
2  amjad   26     76

In [7]:
df["name"]

0      ali
1     shah
2    amjad
Name: name, dtype: str

In [8]:
df["age"]

0    23
1    25
2    26
Name: age, dtype: int64

In [9]:
df.columns

Index(['name', 'age', 'marks'], dtype='str')

In [10]:
df.values

array([['ali', 23, 89],
       ['shah', 25, 78],
       ['amjad', 26, 76]], dtype=object)

In [11]:
df = pd.read_csv("globalAirQuality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [12]:
df.sample()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
5514,2025-11-09 12:25:17.554219,AE,Dubai,25.205,55.271,64.529,63.098,52.09,1.172,58.551,0.892,130,24.435,76.872,0.997

In [13]:
df.head(3)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [14]:
df.tail()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [15]:
df.shape

(18000, 15)

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    18000 non-null  str
 1   country      18000 non-null  str
 2   city         18000 non-null  str
 3   latitude     18000 non-null  float64
 4   longitude    18000 non-null  float64
 5   pm25         18000 non-null  float64
 6   pm10         18000 non-null  float64
 7   no2          18000 non-null  float64
 8   so2          18000 non-null  float64
 9   o3           18000 non-null  float64
 10  co           18000 non-null  float64
 11  aqi          18000 non-null  int64
 12  temperature  18000 non-null  float64
 13  humidity     18000 non-null  float64
 14  wind_speed   18000 non-null  float64
dtypes: float64(11), int64(1), str(3)
memory usage: 2.1 MB

In [17]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [18]:
df.columns

Index(['timestamp', 'country', 'city', 'latitude', 'longitude', 'pm25', 'pm10',
       'no2', 'so2', 'o3', 'co', 'aqi', 'temperature', 'humidity',
       'wind_speed'],
      dtype='str')

In [19]:
df[["country","city","temperature"]]

      country      city  temperature
0          US  New York       18.504
1          US  New York        5.838
2          US  New York       31.833
3          US  New York       23.140
4          US  New York       13.632
...       ...       ...          ...
17995      CH    Zurich        7.079
17996      CH    Zurich       28.734
17997      CH    Zurich       21.951
17998      CH    Zurich       24.042
17999      CH    Zurich        8.529

[18000 rows x 3 columns]

In [20]:
# filter data
df[(df["temperature"]>30) & (df["aqi"]>100)] [["city","temperature","aqi"]]

           city  temperature  aqi
6      New York       36.729  155
7      New York       37.891  115
14     New York       34.481  121
17     New York       36.193  127
25     New York       31.289  113
...         ...          ...  ...
17947    Zurich       32.584  107
17950    Zurich       36.885  140
17975    Zurich       30.761  111
17976    Zurich       30.909  146
17991    Zurich       32.556  104

[2384 rows x 3 columns]

In [21]:
df.loc[0:2]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [22]:
df.loc[0:3,["city","temperature"]]

       city  temperature
0  New York       18.504
1  New York        5.838
2  New York       31.833
3  New York       23.140

In [23]:
df.iloc[0:3]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [24]:
df.iloc[0:3,[1,4]]

  country  longitude
0      US    -74.006
1      US    -74.006
2      US    -74.006

In [25]:
df = pd.read_csv("employee_data.csv")
df

    ID     Name   Age Department  Salary
0    1    Alice  25.0         HR   55000
1    1    Alice  25.0         HR   55000
2    2      Bob  32.0         IT   72000
3    3  Charlie  28.0    Finance   48000
4    4    David  45.0  Marketing   91000
5    5      NaN  38.0         IT   65000
6    6    Frank   NaN    Finance   50000
7    7    Grace  41.0        NaN   82000
8    8   Hannah  26.0  Marketing   47000
9    9      Ian  35.0         IT   75000
10  10    Julia  30.0    Finance   60000

In [26]:
df.nunique()

ID            10
Name           9
Age            9
Department     4
Salary        10
dtype: int64

In [27]:
df.isnull()

       ID   Name    Age  Department  Salary
0   False  False  False       False   False
1   False  False  False       False   False
2   False  False  False       False   False
3   False  False  False       False   False
4   False  False  False       False   False
5   False   True  False       False   False
6   False  False   True       False   False
7   False  False  False        True   False
8   False  False  False       False   False
9   False  False  False       False   False
10  False  False  False       False   False

In [28]:
df.isna()

       ID   Name    Age  Department  Salary
0   False  False  False       False   False
1   False  False  False       False   False
2   False  False  False       False   False
3   False  False  False       False   False
4   False  False  False       False   False
5   False   True  False       False   False
6   False  False   True       False   False
7   False  False  False        True   False
8   False  False  False       False   False
9   False  False  False       False   False
10  False  False  False       False   False

In [29]:
df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [31]:
df

    ID     Name   Age Department  Salary
0    1    Alice  25.0         HR   55000
1    1    Alice  25.0         HR   55000
2    2      Bob  32.0         IT   72000
3    3  Charlie  28.0    Finance   48000
4    4    David  45.0  Marketing   91000
5    5      NaN  38.0         IT   65000
6    6    Frank   NaN    Finance   50000
7    7    Grace  41.0        NaN   82000
8    8   Hannah  26.0  Marketing   47000
9    9      Ian  35.0         IT   75000
10  10    Julia  30.0    Finance   60000

In [32]:
df.drop_duplicates()

    ID     Name   Age Department  Salary
0    1    Alice  25.0         HR   55000
2    2      Bob  32.0         IT   72000
3    3  Charlie  28.0    Finance   48000
4    4    David  45.0  Marketing   91000
5    5      NaN  38.0         IT   65000
6    6    Frank   NaN    Finance   50000
7    7    Grace  41.0        NaN   82000
8    8   Hannah  26.0  Marketing   47000
9    9      Ian  35.0         IT   75000
10  10    Julia  30.0    Finance   60000

In [33]:
df2 = df.copy()

In [34]:
df2

    ID     Name   Age Department  Salary
0    1    Alice  25.0         HR   55000
1    1    Alice  25.0         HR   55000
2    2      Bob  32.0         IT   72000
3    3  Charlie  28.0    Finance   48000
4    4    David  45.0  Marketing   91000
5    5      NaN  38.0         IT   65000
6    6    Frank   NaN    Finance   50000
7    7    Grace  41.0        NaN   82000
8    8   Hannah  26.0  Marketing   47000
9    9      Ian  35.0         IT   75000
10  10    Julia  30.0    Finance   60000

In [35]:
df2.drop_duplicates(inplace=True)
df2

    ID     Name   Age Department  Salary
0    1    Alice  25.0         HR   55000
2    2      Bob  32.0         IT   72000
3    3  Charlie  28.0    Finance   48000
4    4    David  45.0  Marketing   91000
5    5      NaN  38.0         IT   65000
6    6    Frank   NaN    Finance   50000
7    7    Grace  41.0        NaN   82000
8    8   Hannah  26.0  Marketing   47000
9    9      Ian  35.0         IT   75000
10  10    Julia  30.0    Finance   60000

In [36]:
df.dropna()

    ID     Name   Age Department  Salary
0    1    Alice  25.0         HR   55000
1    1    Alice  25.0         HR   55000
2    2      Bob  32.0         IT   72000
3    3  Charlie  28.0    Finance   48000
4    4    David  45.0  Marketing   91000
8    8   Hannah  26.0  Marketing   47000
9    9      Ian  35.0         IT   75000
10  10    Julia  30.0    Finance   60000

In [38]:
df.fillna(4)

    ID     Name   Age Department  Salary
0    1    Alice  25.0         HR   55000
1    1    Alice  25.0         HR   55000
2    2      Bob  32.0         IT   72000
3    3  Charlie  28.0    Finance   48000
4    4    David  45.0  Marketing   91000
5    5        4  38.0         IT   65000
6    6    Frank   4.0    Finance   50000
7    7    Grace  41.0          4   82000
8    8   Hannah  26.0  Marketing   47000
9    9      Ian  35.0         IT   75000
10  10    Julia  30.0    Finance   60000

In [39]:
df.ffill()

    ID     Name   Age Department  Salary
0    1    Alice  25.0         HR   55000
1    1    Alice  25.0         HR   55000
2    2      Bob  32.0         IT   72000
3    3  Charlie  28.0    Finance   48000
4    4    David  45.0  Marketing   91000
5    5    David  38.0         IT   65000
6    6    Frank  38.0    Finance   50000
7    7    Grace  41.0    Finance   82000
8    8   Hannah  26.0  Marketing   47000
9    9      Ian  35.0         IT   75000
10  10    Julia  30.0    Finance   60000

In [40]:
df.bfill()

    ID     Name   Age Department  Salary
0    1    Alice  25.0         HR   55000
1    1    Alice  25.0         HR   55000
2    2      Bob  32.0         IT   72000
3    3  Charlie  28.0    Finance   48000
4    4    David  45.0  Marketing   91000
5    5    Frank  38.0         IT   65000
6    6    Frank  41.0    Finance   50000
7    7    Grace  41.0  Marketing   82000
8    8   Hannah  26.0  Marketing   47000
9    9      Ian  35.0         IT   75000
10  10    Julia  30.0    Finance   60000

In [42]:
avg_age = df["Age"].mean()
avg_age

np.float64(32.5)

In [45]:
df2 = df["Age"] = df["Age"].fillna(avg_age)

In [46]:
df2

0     25.0
1     25.0
2     32.0
3     28.0
4     45.0
5     38.0
6     32.5
7     41.0
8     26.0
9     35.0
10    30.0
Name: Age, dtype: float64

In [47]:
df["Name"].str.capitalize()

0       Alice
1       Alice
2         Bob
3     Charlie
4       David
5         NaN
6       Frank
7       Grace
8      Hannah
9         Ian
10      Julia
Name: Name, dtype: str

In [48]:
df["Name"].str.contains("frank", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
Name: Name, dtype: bool

In [49]:
df["Name"].str.upper()

0       ALICE
1       ALICE
2         BOB
3     CHARLIE
4       DAVID
5         NaN
6       FRANK
7       GRACE
8      HANNAH
9         IAN
10      JULIA
Name: Name, dtype: str

In [50]:
df["Name"].str.lower()

0       alice
1       alice
2         bob
3     charlie
4       david
5         NaN
6       frank
7       grace
8      hannah
9         ian
10      julia
Name: Name, dtype: str

In [51]:
df["Name"].isnull().sum()

np.int64(1)

In [52]:
df.query("Age >= 25 and Department == 'HR'")

   ID   Name   Age Department  Salary
0   1  Alice  25.0         HR   55000
1   1  Alice  25.0         HR   55000

In [54]:
df.query("Age <= 24 or Salary >= 55000")

    ID   Name   Age Department  Salary
0    1  Alice  25.0         HR   55000
1    1  Alice  25.0         HR   55000
2    2    Bob  32.0         IT   72000
4    4  David  45.0  Marketing   91000
5    5    NaN  38.0         IT   65000
7    7  Grace  41.0        NaN   82000
9    9    Ian  35.0         IT   75000
10  10  Julia  30.0    Finance   60000